### ISSUE TITLE
Warning about lack of Minimize, Maximize icons in Gnome

### ISSUE THREAD

**Issue by Tiptoeing3282** [BrewingWeasel/Kalba#56]
It's not the fault of Kalba, I think, but of Gnome developers stubborness, in order for Maximize and Minimize icons to appear in Kalba under Gnome, you'll need to go Gnome Tweaks -> Windows -> Maximize/Minimize icons.
There should be a warning in the documentation to do that for Gnome users. Otherwise, Kalba's window size is fixed.
![Screenshot from 2024-09-04 16-05-09](https://github.com/user-attachments/assets/b1acf26f-7894-4d6a-8688-9809ad1c43c8)

![Screenshot from 2024-09-04 16-06-21](https://github.com/user-attachments/assets/5c5f2fd9-0678-4355-b6c7-6fe9b67e4629)

**Comment by BrewingWeasel** [comment]
Oooh good catch thank you! It would really be nice if there was a way to get around this without the user (classic GNOME lol), but for now adding some sort of "common problems" page or something in the docs sounds like a good fix! I can also maybe try to find some better way when I have more time

**Comment by BrewingWeasel** [comment]
Added the docs.
Thanks again for the issue!
